name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker (with CI network override)
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d --build

      - name: Install Composer dependencies inside container
        run: docker compose exec -T app composer install --no-interaction --prefer-dist

      - name: Run PHPCS
        run: docker compose exec -T app composer phpcs

      - name: Run PHPStan
        run: docker compose exec -T app composer phpstan

      - name: Run PHPUnit
        run: docker compose exec -T app sh composer phpunit
